In [1]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
df=pd.read_csv("/Users/anshika/Desktop/smart_city_prediction_ml/traffic/data/Metro_Interstate_Traffic_Volume.csv")
df

,holiday,temp,rain_1h,snow_1h,clouds_all,weather_main,weather_description,date_time,traffic_volume
0,NaN,288.28,0.0,0.0,40,Clouds,scattered clouds,2012-10-02 09:00:00,5545
1,NaN,289.36,0.0,0.0,75,Clouds,broken clouds,2012-10-02 10:00:00,4516
2,NaN,289.58,0.0,0.0,90,Clouds,overcast clouds,2012-10-02 11:00:00,4767
3,NaN,290.13,0.0,0.0,90,Clouds,overcast clouds,2012-10-02 12:00:00,5026
4,NaN,291.14,0.0,0.0,75,Clouds,broken clouds,2012-10-02 13:00:00,4918
...,...,...,...,...,...,...,...,...,...
48199,NaN,283.45,0.0,0.0,75,Clouds,broken clouds,2018-09-30 19:00:00,3543
48200,NaN,282.76,0.0,0.0,90,Clouds,overcast clouds,2018-09-30 20:00:00,2781
48201,NaN,282.73,0.0,0.0,90,Thunderstorm,proximity thunderstorm,2018-09-30 21:00:00,2159
48202,NaN,282.09,0.0,0.0,90,Clouds,overcast clouds,2018-09-30 22:00:00,1450
48203,NaN,282.12,0.0,0.0,90,Clouds,overcast clouds,2018-09-30 23:00:00,954

In [2]:
##data info gathering
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48204 entries, 0 to 48203
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   holiday              61 non-null     object
 1   temp                 48204 non-null  float64
 2   rain_1h              48204 non-null  float64
 3   snow_1h              48204 non-null  float64
 4   clouds_all           48204 non-null  int64
 5   weather_main         48204 non-null  object
 6   weather_description  48204 non-null  object
 7   date_time            48204 non-null  object
 8   traffic_volume       48204 non-null  int64
dtypes: float64(3), int64(2), object(4)
memory usage: 3.3+ MB

In [3]:
df.shape

(48204, 9)

In [4]:
df.holiday.value_counts()

holiday
Labor Day                    7
Thanksgiving Day             6
Christmas Day                6
New Years Day                6
Martin Luther King Jr Day    6
Columbus Day                 5
Veterans Day                 5
Washingtons Birthday         5
Memorial Day                 5
Independence Day             5
State Fair                   5
Name: count, dtype: int64

In [5]:
df.describe()

               temp       rain_1h       snow_1h    clouds_all  traffic_volume
count  48204.000000  48204.000000  48204.000000  48204.000000    48204.000000
mean     281.205870      0.334264      0.000222     49.362231     3259.818355
std       13.338232     44.789133      0.008168     39.015750     1986.860670
min        0.000000      0.000000      0.000000      0.000000        0.000000
25%      272.160000      0.000000      0.000000      1.000000     1193.000000
50%      282.450000      0.000000      0.000000     64.000000     3380.000000
75%      291.806000      0.000000      0.000000     90.000000     4933.000000
max      310.070000   9831.300000      0.510000    100.000000     7280.000000

In [6]:
df.head()

,holiday,temp,rain_1h,snow_1h,clouds_all,weather_main,weather_description,date_time,traffic_volume
0,NaN,288.28,0.0,0.0,40,Clouds,scattered clouds,2012-10-02 09:00:00,5545
1,NaN,289.36,0.0,0.0,75,Clouds,broken clouds,2012-10-02 10:00:00,4516
2,NaN,289.58,0.0,0.0,90,Clouds,overcast clouds,2012-10-02 11:00:00,4767
3,NaN,290.13,0.0,0.0,90,Clouds,overcast clouds,2012-10-02 12:00:00,5026
4,NaN,291.14,0.0,0.0,75,Clouds,broken clouds,2012-10-02 13:00:00,4918

In [7]:
df.tail()

,holiday,temp,rain_1h,snow_1h,clouds_all,weather_main,weather_description,date_time,traffic_volume
48199,NaN,283.45,0.0,0.0,75,Clouds,broken clouds,2018-09-30 19:00:00,3543
48200,NaN,282.76,0.0,0.0,90,Clouds,overcast clouds,2018-09-30 20:00:00,2781
48201,NaN,282.73,0.0,0.0,90,Thunderstorm,proximity thunderstorm,2018-09-30 21:00:00,2159
48202,NaN,282.09,0.0,0.0,90,Clouds,overcast clouds,2018-09-30 22:00:00,1450
48203,NaN,282.12,0.0,0.0,90,Clouds,overcast clouds,2018-09-30 23:00:00,954

In [8]:
## data cleaning
df.duplicated().sum()

np.int64(17)

In [9]:
df.drop_duplicates(inplace=True)

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.isnull().sum()

holiday                48126
temp                       0
rain_1h                    0
snow_1h                    0
clouds_all                 0
weather_main               0
weather_description        0
date_time                  0
traffic_volume             0
dtype: int64

In [12]:
df = pd.get_dummies(
     df,
    columns=['holiday','weather_main','weather_description'],
    drop_first=True
)

In [13]:
##feature engineering
df['date_time'] = pd.to_datetime(df['date_time'])
df['hour'] = df['date_time'].dt.hour
df['day'] = df['date_time'].dt.day
df['month'] = df['date_time'].dt.month
df['dayofweek'] = df['date_time'].dt.dayofweek
df.drop('date_time', axis=1, inplace=True)

In [14]:
df.head()

,temp,rain_1h,snow_1h,clouds_all,traffic_volume,holiday_Columbus Day,holiday_Independence Day,holiday_Labor Day,holiday_Martin Luther King Jr Day,holiday_Memorial Day,...,weather_description_thunderstorm with drizzle,weather_description_thunderstorm with heavy rain,weather_description_thunderstorm with light drizzle,weather_description_thunderstorm with light rain,weather_description_thunderstorm with rain,weather_description_very heavy rain,hour,day,month,dayofweek
0,288.28,0.0,0.0,40,5545,False,False,False,False,False,...,False,False,False,False,False,False,9,2,10,1
1,289.36,0.0,0.0,75,4516,False,False,False,False,False,...,False,False,False,False,False,False,10,2,10,1
2,289.58,0.0,0.0,90,4767,False,False,False,False,False,...,False,False,False,False,False,False,11,2,10,1
3,290.13,0.0,0.0,90,5026,False,False,False,False,False,...,False,False,False,False,False,False,12,2,10,1
4,291.14,0.0,0.0,75,4918,False,False,False,False,False,...,False,False,False,False,False,False,13,2,10,1

In [15]:
##X and Y
X=df.drop(['traffic_volume'], axis=1)
y=df['traffic_volume']

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [17]:
##Random Forest Regressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, accuracy_score

model = RandomForestRegressor( n_estimators=200,max_depth=15,random_state=42)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print("R² Score:", r2_score(y_test, y_pred))

R² Score: 0.9620711336460899

In [18]:
##Linear Regression
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(X_train, y_train)
y_pred = reg.predict(X_test)

In [19]:
print("r2_score:", r2_score(y_test, y_pred))

r2_score: -3.4558223531838452

In [20]:
##DECISION TREE Regression
from sklearn.tree import DecisionTreeRegressor
regressor=DecisionTreeRegressor(random_state=42)
regressor.fit(X_train,y_train)

DecisionTreeRegressor(random_state=42)

In [21]:
y_pred=regressor.predict(X_test)
regressor.score(X_test,y_test)

0.9398512558899464

In [23]:
# SVR Model
from sklearn.svm import SVR
model = SVR(kernel='rbf')
model.fit(X_train, y_train)

SVR()

In [24]:
y_pred = model.predict(X_test)  ### Prediction

In [25]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

print("R2 Score :", r2_score(y_test, y_pred))

R2 Score : 0.007277085130287686

In [27]:
##knn regressor
from sklearn.neighbors import KNeighborsRegressor
model=KNeighborsRegressor(n_neighbors=15)
model.fit(X_train,y_train)

KNeighborsRegressor(n_neighbors=15)

In [28]:
pred = model.predict(X_test)
from sklearn.metrics import r2_score
print(r2_score(y_test, pred))

0.8138191386884617

In [31]:
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsRegressor
param_grid = {
    'n_neighbors': [3, 5, 7, 9, 11, 15],
    'weights': ['uniform', 'distance'],
    'metric': ['euclidean', 'manhattan']
    }
grid=GridSearchCV(
    KNeighborsRegressor(n_neighbors=15),
    param_grid,
    cv=5,
    scoring='r2',
    n_jobs=-1,
)
grid.fit(X_train,y_train)
print("best params:", grid.best_params_)
print("best score:", grid.best_score_)

best params: {'metric': 'euclidean', 'n_neighbors': 5, 'weights': 'distance'}
best score: 0.8495873364865354

In [33]:
best_kn=grid.best_estimator_
y_pred=best_kn.predict(X_test)
from sklearn.metrics import r2_score
print("tuned knn regressor:",r2_score(y_test, y_pred))

tuned knn regressor: 0.8688527563952428